import type { Resort } from "@/core/schemas";

export const resorts: Resort[] = [
  // ==========================================
  // 3-STAR CATEGORY (₹4,000 – ₹6,000 / night)
  // ==========================================
  {
    id: "serenity-resort",
    slug: "serenity-resort",
    name: "Serenity Corbett Resort",
    category: "3-star",
    starRating: 3,
    priceRange: {
      minPriceINR: 4000,
      maxPriceINR: 6000,
      priceDisplay: "₹4,000 – ₹6,000",
      priceNote: "Per room / night — EP or CP plan options available (taxes extra)",
    },
    location: {
      area: "Dhikuli, Ramnagar",
      address: "Ranikhet Road, Village Dhikuli, Ramnagar, District Nainital, Uttarakhand - 244715",
      distanceFromStation: "8 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Safari Gate (5 km)", "Garjiya Gate (3 km)"],
      riverFront: false,
      riverProximity: "500 meters from the Kosi River bank",
    },
    tagline: "Eco-friendly boutique retreat nestled amidst lush mango orchards in Dhikuli",
    overview:
      "Serenity Corbett Resort is a boutique wildlife retreat situated along the scenic Ranikhet corridor in Dhikuli. Embraced by mature mango and litchi orchards with views of the Himalayan foothills, it offers comfortable cottage-style stays with solar-powered eco-infrastructure. Guests enjoy relaxed open-air dining at the Gol Ghar restaurant, clean swimming pool facilities, and rapid access to the Bijrani safari gate.",
    amenities: [
      "Swimming Pool",
      "Gol Ghar Open-Air Restaurant",
      "Organic Vegetable & Herb Garden",
      "Solar Water Heating System",
      "Indoor Recreational Games",
      "Landscaped Lawns & Orchard Walkways",
      "Bonfire Evenings & Barbecue",
      "Safari Booking & Naturalist Guidance",
      "Free High-Speed Wi-Fi",
      "On-Site Complimentary Parking",
    ],
    roomTypes: [
      "Garden Facing Super Deluxe Room",
      "Poolside Interconnected Family Room",
      "Family Attic Cottage",
    ],
    checkInTime: "12:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Located just 5 km from the popular Bijrani safari zone entry gate",
      "Rustic Gol Ghar dining set within an organic mango grove",
      "Sustainable hospitality practices featuring solar power & organic produce",
      "Ideal accommodation for families and wildlife photographers on a budget",
    ],
    websiteUrl: "https://serenitycorbett.com",
    rating: 4.1,
    reviewCount: 380,
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Serenity Corbett Resort Dhikuli — 3-Star Jungle Stay | Rates & Safari Packages",
    seoDescription:
      "Book Serenity Corbett Resort in Dhikuli, Ramnagar. 3-star mango orchard resort just 5 km from Bijrani Gate. Swimming pool, Gol Ghar dining, rooms from ₹4,000/night.",
    seoKeywords: [
      "serenity resort corbett",
      "serenity resort dhikuli",
      "3 star resorts in jim corbett",
      "resorts near bijrani gate",
      "corbett budget jungle stay",
    ],
  },
  {
    id: "wildlife-stayz-by-corbett-treff",
    slug: "wildlife-stayz-by-corbett-treff",
    name: "Wildlife Stayz by Corbett Treff",
    category: "3-star",
    starRating: 3,
    priceRange: {
      minPriceINR: 4000,
      maxPriceINR: 6000,
      priceDisplay: "₹4,000 – ₹6,000",
      priceNote: "Per room / night — double occupancy (meals as per plan)",
    },
    location: {
      area: "Dhikuli, Ramnagar",
      address: "Ramnagar-Ranikhet Road (NH 121), Dhikuli, Ramnagar, Nainital, Uttarakhand - 244715",
      distanceFromStation: "9 km from Ramnagar Railway Station",
      nearestSafariGates: ["Garjiya Gate (1.4 km)", "Bijrani Gate (6 km)"],
      riverFront: false,
      riverProximity: "Short 5-minute stroll to Kosi Riverbed",
    },
    tagline: "Vibrant wildlife hub positioned minutes away from Garjiya Gate",
    overview:
      "Wildlife Stayz by Corbett Treff (formerly Corbett Treff Resort) is a welcoming safari retreat located on the Dhikuli main highway corridor. Surrounded by towering sal woodlands, the property features spacious independent cottages, a central outdoor swimming pool, and an atmospheric restaurant serving regional Kumaoni and Indian cuisine. Its prime location just 1.4 km from Garjiya Gate makes dawn safari transfers seamless.",
    amenities: [
      "Outdoor Swimming Pool",
      "Multi-Cuisine Restaurant",
      "Bonfire Pit with Musical Evenings",
      "Table Tennis & Badminton Court",
      "Jungle Trekking & Bird Watching",
      "24-Hour Power Backup",
      "Safari Desk & Travel Assistance",
      "Free High-Speed Wi-Fi",
      "Private On-Site Parking",
      "Doctor on Call",
    ],
    roomTypes: [
      "Deluxe Cottage",
      "Premium Garden Room with Balcony",
      "Family Suite with Forest View",
    ],
    checkInTime: "12:00 PM",
    checkOutTime: "10:30 AM",
    highlights: [
      "Only 1.4 km from Garjiya Safari Gate and Garjiya Devi Temple",
      "Warm wildlife-lodge ambiance with bonfire sessions and nature walks",
      "Prime highway connectivity with quick transfers to all central zones",
      "Excellent value for wildlife safari enthusiasts and birders",
    ],
    websiteUrl: "https://treffresort.com",
    rating: 4.0,
    reviewCount: 420,
    image:
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "Wildlife Stayz by Corbett Treff — Dhikuli Resort Near Garjiya Gate",
    seoDescription:
      "Stay at Wildlife Stayz by Corbett Treff in Dhikuli. Affordable 3-star cottages 1.4 km from Garjiya Gate. Pool, bonfire, multi-cuisine dining from ₹4,000–₹6,000.",
    seoKeywords: [
      "wildlife stayz corbett treff",
      "corbett treff resort",
      "hotels in dhikuli ramnagar",
      "resorts near garjiya gate",
      "jim corbett 3 star hotel",
    ],
  },
  {
    id: "arch-the-bakhli-resort",
    slug: "arch-the-bakhli-resort",
    name: "Arch The Baakhli Resort",
    category: "3-star",
    starRating: 3,
    priceRange: {
      minPriceINR: 4000,
      maxPriceINR: 6000,
      priceDisplay: "₹4,000 – ₹6,000",
      priceNote: "Per room / night — seasonal variations apply",
    },
    location: {
      area: "Khushalpur / Dhikuli Edge",
      address: "Khasra No 17/1/2, Khushalpur Shahbazpur, Guljarpur Ramsingh, Ramnagar, Nainital, Uttarakhand - 263140",
      distanceFromStation: "6 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Gate (4.5 km)", "Jhirna Gate (14 km)"],
      riverFront: false,
      riverProximity: "Panoramic views of Kosi riverbed and adjacent sal forest",
    },
    tagline: "Authentic Kumaoni heritage courtyard architecture overlooking Kosi valley",
    overview:
      "Arch The Baakhli Resort is uniquely designed around the traditional Kumaoni 'Baakhli' architectural pattern — a continuous cluster of stone cottages flanking a shared community promenade. Perched along the edge of the Corbett forest foothills with sweeping perspectives of the river valley, it blends local architectural charm with modern guest amenities including an outdoor swimming pool, fitness zone, and multi-cuisine restaurant.",
    amenities: [
      "Outdoor Swimming Pool with Kids' Splash Section",
      "Heritage Architecture Courtyard & Promenade",
      "Promenade Multi-Cuisine Dining",
      "Fitness Center & Activity Room",
      "Jacuzzi Suites (Select Categories)",
      "Karaoke & Children's Play Area",
      "Banquet & Conference Hall",
      "Free Wi-Fi Across Property",
      "Luggage Storage & Concierge",
      "Secure Valet Parking",
    ],
    roomTypes: [
      "Deluxe Heritage Room",
      "Duplex Family Suite",
      "Royal Baakhli Jacuzzi Suite",
    ],
    checkInTime: "01:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Traditional Kumaoni 'Baakhli' courtyard design offering cultural depth",
      "Edge-of-foothills vantage point with forest and river vistas",
      "Spacious duplex suites suitable for multi-generational families",
      "Private Jacuzzi options available in premium suites",
    ],
    websiteUrl: "https://thebaakhlicorbett.com",
    rating: 4.2,
    reviewCount: 310,
    image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "Arch The Baakhli Resort Corbett — Traditional Kumaoni Heritage Stay",
    seoDescription:
      "Discover Arch The Baakhli Resort in Ramnagar. Traditional Kumaoni style stone cottages, swimming pool, forest views, family duplex suites from ₹4,000–₹6,000.",
    seoKeywords: [
      "arch the bakhli resort",
      "the baakhli resort corbett",
      "kumaoni heritage resort corbett",
      "resorts near ramnagar railway station",
      "family resort in corbett",
    ],
  },
  {
    id: "aura-by-xprience",
    slug: "aura-by-xprience",
    name: "Aura By Xprience (Xomotel Corbett Aura)",
    category: "3-star",
    starRating: 3,
    priceRange: {
      minPriceINR: 4000,
      maxPriceINR: 6000,
      priceDisplay: "₹4,000 – ₹6,000",
      priceNote: "Per room / night — standard double occupancy",
    },
    location: {
      area: "Sawaldey, Jhirna Road",
      address: "Sawaldey Village, Ramnagar-Jhirna Road, Nainital, Uttarakhand - 244715",
      distanceFromStation: "9 km from Ramnagar Railway Station",
      nearestSafariGates: ["Dhela Safari Gate (5.5 km)", "Jhirna Safari Gate (6 km)"],
      riverFront: false,
      riverProximity: "Surrounded by rural orchards and forest buffer streams",
    },
    tagline: "Earthy mud-cottage retreat bordering the southern safari corridors",
    overview:
      "Aura By Xprience (also known as Xomotel Corbett Aura Resort) is located in the peaceful rural settlement of Sawaldey on the approach to Jhirna and Dhela zones. The resort embraces nature-centric design with textured mud huts, independent thatch-roof cottages, and open green manicured lawns. A refreshing pool, wellness spa treatments, and farm-fresh organic meals make it a quiet sanctuary for wildlife tourists visiting the southern Corbett zones.",
    amenities: [
      "Central Swimming Pool",
      "Spa Therapy & Ayurvedic Wellness",
      "Multi-Cuisine Farm-Fresh Restaurant",
      "Private Plunge Pool (Select Cottages)",
      "Indoor Games (Billiards, Carrom, Chess)",
      "Outdoor Badminton & Lawn Sports",
      "Pet-Friendly Facilities",
      "24/7 Power Backup",
      "Safari Assistance for Jhirna & Dhela",
      "Complimentary Wi-Fi",
    ],
    roomTypes: [
      "Luxury Mud Hut Cottage",
      "Forest View Deluxe Room",
      "Club Cottage with Private Plunge Pool",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Prime proximity to round-the-year safari zones: Jhirna and Dhela",
      "Unique mud cottage architecture offering natural thermal cooling",
      "Pet-friendly property surrounded by peaceful agrarian landscapes",
      "Private plunge pool accommodations in the luxury cottage category",
    ],
    websiteUrl: "https://xomotel.com",
    rating: 4.1,
    reviewCount: 290,
    image:
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "Aura By Xprience Corbett — Mud Cottages Near Jhirna & Dhela Gate",
    seoDescription:
      "Experience Aura By Xprience resort in Sawaldey, Ramnagar. Mud cottages, plunge pools, pet-friendly amenities near Jhirna safari gate from ₹4,000–₹6,000/night.",
    seoKeywords: [
      "aura by xprience corbett",
      "xomotel corbett aura",
      "resorts near jhirna gate",
      "resorts near dhela gate",
      "pet friendly resorts jim corbett",
    ],
  },
  {
    id: "la-savana-resort",
    slug: "la-savana-resort",
    name: "La Savana Resort & Spa",
    category: "3-star",
    starRating: 3,
    priceRange: {
      minPriceINR: 4000,
      maxPriceINR: 6000,
      priceDisplay: "₹4,000 – ₹6,000",
      priceNote: "Per room / night — CP/MAP plans available",
    },
    location: {
      area: "Dhikuli, Ramnagar",
      address: "Ranikhet Road, Dhikuli, Ramnagar, District Nainital, Uttarakhand - 244715",
      distanceFromStation: "7.5 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Gate (4 km)", "Garjiya Gate (3.5 km)"],
      riverFront: false,
      riverProximity: "Adjacent to Corbett buffer reserve near Kosi River",
    },
    tagline: "Comfortable scenic base in Dhikuli with panoramic mountain vistas",
    overview:
      "La Savana Resort & Spa by DL Hotels is situated along the main Ranikhet Road in Dhikuli, bordering the Corbett buffer forest. With 36 contemporary appointed guestrooms and suites, the property caters to leisure travelers and corporate retreats. Well-kept open lawns, a multi-cuisine indoor dining room, conference halls, and a dedicated kids' play zone provide a balanced holiday stay in the heart of Corbett's tourist district.",
    amenities: [
      "Indoor Swimming Pool",
      "Full-Service Spa & Wellness Therapy",
      "Multi-Cuisine Dining Restaurant",
      "Spacious Event Lawns & Banquet Hall",
      "Conference Facilities for Corporate Offsites",
      "Children's Play Area & Garden Playground",
      "Recreation Room (Billiards & Table Tennis)",
      "Evening Bonfire Pit",
      "24-Hour Front Desk & Concierge",
      "Doctor on Call",
      "Safari Booking Support",
      "Free Wi-Fi & Internet Access",
      "Ample Secure Vehicle Parking",
    ],
    roomTypes: [
      "Deluxe Room",
      "Super Deluxe Room with Balcony",
      "Executive Mountain View Suite",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "36 modern air-conditioned rooms featuring private garden and hill balconies",
      "Central Dhikuli location with swift transit to Bijrani and Garjiya gates",
      "Dedicated corporate event and banquet facilities",
      "Affordable tariff delivering high comfort and attentive room service",
    ],
    rating: 3.9,
    reviewCount: 240,
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "La Savana Resort & Spa Dhikuli — Budget-Friendly Corbett Stay",
    seoDescription:
      "Book La Savana Resort in Dhikuli, Jim Corbett. 36 comfortable rooms with mountain views, conference facilities, and quick safari gate access from ₹4,000–₹6,000.",
    seoKeywords: [
      "la savana resort corbett",
      "la savana resort dhikuli",
      "budget resort in dhikuli",
      "corbett conference resort",
      "hotel near bijrani gate",
    ],
  },

  // ==========================================
  // 4-STAR CATEGORY (₹6,000 – ₹10,000 / night)
  // ==========================================
  {
    id: "la-perle-river-resort",
    slug: "la-perle-river-resort",
    name: "La Perle River Resort",
    category: "4-star",
    starRating: 4,
    priceRange: {
      minPriceINR: 6000,
      maxPriceINR: 7000,
      priceDisplay: "₹6,000 – ₹7,000",
      priceNote: "Per room / night — includes breakfast & morning tea",
    },
    location: {
      area: "Dhikuli, Riverfront",
      address: "Village Ladhuachaur, P.O. Dhikuli, Ramnagar, District Nainital, Uttarakhand - 244715",
      distanceFromStation: "6 km from Ramnagar Railway Station",
      nearestSafariGates: ["Garjiya Gate (3 km)", "Bijrani Gate (5 km)"],
      riverFront: true,
      riverProximity: "Direct private shoreline access to the Kosi River",
    },
    tagline: "Sprawling 7-acre mango orchard riverfront resort on the banks of Kosi",
    overview:
      "La Perle River Resort is an expansive 4-star riverfront haven spread across more than 7 acres of manicured lawns and heritage mango orchards in Ladhuachaur, Dhikuli. Offering direct walking access to the pebble banks of the Kosi River, guests wake up to mist over the water and Himalayan bird songs. The resort features themed luxury cottage blocks (Leopard Lair, Tiger Den), riverside dining at Bagh Haweli, a resort swimming pool, and extensive corporate banquet grounds.",
    amenities: [
      "Direct Kosi River Beach Access",
      "Large Outdoor Swimming Pool with Sun Deck",
      "Bagh Haweli Riverside Multi-Cuisine Restaurant",
      "7-Acre Landscaped Mango Orchards",
      "Indoor Recreation & Fitness Room",
      "Large Conference & Destination Wedding Lawns",
      "Evening Cultural Bonfire Sessions",
      "Jeep Safari & Canter Booking Assistance",
      "Free High-Speed Wi-Fi",
      "Valet Parking & 24/7 Security",
    ],
    roomTypes: [
      "Leopard Lair Cottage",
      "Tiger Den River View Room",
      "Elephant Park Garden Villa",
    ],
    checkInTime: "01:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Direct private access to the crystalline Kosi River shoreline",
      "Over 7 acres of shaded mango orchards and tranquil green lawns",
      "Bagh Haweli restaurant serving authentic regional and global fare",
      "Themed wilderness room categories with river and pool views",
    ],
    websiteUrl: "https://laperlehotels.com",
    rating: 4.3,
    reviewCount: 680,
    image:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "La Perle River Resort Jim Corbett — 4-Star Kosi Riverfront Stay",
    seoDescription:
      "Stay at La Perle River Resort on the banks of the Kosi River in Dhikuli. 7-acre mango orchard, river view rooms, swimming pool from ₹6,000–₹7,000/night.",
    seoKeywords: [
      "la perle river resort corbett",
      "riverside resort jim corbett",
      "kosi river resort dhikuli",
      "4 star resort in jim corbett",
      "la perle resort booking",
    ],
  },
  {
    id: "river-heritage-resort",
    slug: "river-heritage-resort",
    name: "River Heritage Resort",
    category: "4-star",
    starRating: 4,
    priceRange: {
      minPriceINR: 9000,
      maxPriceINR: 10000,
      priceDisplay: "₹9,000 – ₹10,000",
      priceNote: "Per room / night — premium riverfront inventory (MAP/AP plans available)",
    },
    location: {
      area: "Ladwa Chaur, Dhikuli",
      address: "Village Ladwa Chaur, P.O. Dhikuli, Ramnagar, Uttarakhand - 244715",
      distanceFromStation: "9 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Safari Gate (4.5 km)", "Garjiya Gate (2.5 km)"],
      riverFront: true,
      riverProximity: "Front-row panoramic riverfront setting along Kosi River",
    },
    tagline: "Eco-luxury heritage retreat blending Kumaoni grandeur with Kosi river serenity",
    overview:
      "River Heritage Resort is a boutique 4-star luxury property comprising 52 eco-luxury rooms and suites in Dhikuli. Positioned along a scenic bend of the Kosi River, the resort blends traditional Kumaoni stone-and-timber craftsmanship with contemporary upscale amenities. Featuring a year-round outdoor pool, comprehensive Ayurvedic wellness spa, fine-dining restaurant, and manicured riverside terraces, it is among Corbett's most scenic mid-to-high luxury destinations.",
    amenities: [
      "Full-Service Ayurvedic & Holistic Spa",
      "Year-Round Outdoor Swimming Pool",
      "Riverside Fine-Dining Multi-Cuisine Restaurant",
      "Private River Deck with Scenic Seating",
      "Barbecue Grills & Riverside Picnic Areas",
      "Soundproof Luxury Rooms with River Views",
      "24-Hour Concierge & Private Check-In",
      "Grand Wedding & Conference Lawns",
      "High-Speed Wi-Fi Throughout",
      "Complimentary Valet Parking",
    ],
    roomTypes: [
      "Heritage Riverview Luxury Room",
      "Premium Garden Cottage",
      "Royal Riverfront Family Suite",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "52 premium soundproof rooms crafted with eco-luxury materials",
      "Full-service spa offering curated herbal therapies and hot stone massages",
      "Front-row views of the flowing Kosi River and forested hills",
      "High guest satisfaction ratings for culinary quality and riverside tranquility",
    ],
    websiteUrl: "https://riverheritageresort.com",
    rating: 4.5,
    reviewCount: 520,
    image:
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "River Heritage Resort Dhikuli — Luxury Kosi Riverfront Property",
    seoDescription:
      "Book River Heritage Resort in Dhikuli, Corbett. 52 eco-luxury rooms on the Kosi riverbank, Ayurvedic spa, swimming pool. Premium stay ₹9,000–₹10,000/night.",
    seoKeywords: [
      "river heritage resort corbett",
      "luxury resort in dhikuli",
      "kosi riverfront resort corbett",
      "river heritage resort ramnagar",
      "4 star luxury resort corbett",
    ],
  },
  {
    id: "avn-sarovar-portico",
    slug: "avn-sarovar-portico",
    name: "AVN Sarovar Portico Jim Corbett",
    category: "4-star",
    starRating: 4,
    priceRange: {
      minPriceINR: 8000,
      maxPriceINR: 9000,
      priceDisplay: "₹8,000 – ₹9,000",
      priceNote: "Per room / night — signature Sarovar branded hospitality",
    },
    location: {
      area: "Dhikuli, Ranikhet Road",
      address: "Khasra No. 284, Village Dhikuli, Ramnagar, Nainital, Uttarakhand - 244715",
      distanceFromStation: "8 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Gate (4 km)", "Garjiya Gate (3 km)"],
      riverFront: true,
      riverProximity: "Perched along the Kosi River with panoramic rooftop vistas",
    },
    tagline: "Contemporary branded elegance with signature rooftop dining over Kosi River",
    overview:
      "AVN Sarovar Portico (also branded as ABN Sarovar Portico) brings Sarovar Hotels' trusted 4-star hospitality to the prime Dhikuli belt. The resort features modern designer rooms and cottages, the signature 'Kosi Spa' offering relaxing therapies, a landscaped swimming pool, and the standout 'Saffron' rooftop dining lounge which commands unbroken panoramic views of the Kosi River and dense Sal-clad Himalayan foothills. Its expansive venues make it a top choice for destination weddings and executive corporate offsites.",
    amenities: [
      "Outdoor Swimming Pool & Sun Deck",
      "Signature 'Kosi Spa' & Salon",
      "'Saffron' Rooftop Venue Overlooking River",
      "All-Day Multi-Cuisine Restaurant & Cafe Lounge",
      "State-of-the-Art Fitness Center",
      "Grand Event Lawns (Up to 200 Guests)",
      "High-Tech Conference & Board Rooms",
      "24-Hour In-Room Dining & Room Service",
      "Complimentary High-Speed Wi-Fi",
      "Dedicated Accessible Facilities",
    ],
    roomTypes: [
      "Deluxe Garden View Room",
      "Superior River View Room",
      "Executive Sarovar Suite with Balcony",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "12:00 PM",
    highlights: [
      "Backed by Sarovar Hotels' trusted nationwide hospitality standard",
      "Signature 'Saffron' rooftop dining with 360-degree river and valley views",
      "Full-service 'Kosi Spa' and salon for complete rejuvenation after safaris",
      "Centrally positioned in Dhikuli with seamless safari gate connections",
    ],
    websiteUrl: "https://sarovarhotels.com",
    rating: 4.4,
    reviewCount: 750,
    image:
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "AVN Sarovar Portico Corbett Dhikuli — 4-Star Luxury Resort",
    seoDescription:
      "Experience AVN Sarovar Portico in Dhikuli, Jim Corbett. Rooftop dining with river views, Kosi Spa, luxury cottages from ₹8,000–₹9,000/night. Book direct.",
    seoKeywords: [
      "avn sarovar portico corbett",
      "abn sarovar portico jim corbett",
      "sarovar hotel ramnagar",
      "4 star hotel in dhikuli",
      "resorts with rooftop restaurant corbett",
    ],
  },
  {
    id: "banyan-retreat",
    slug: "banyan-retreat",
    name: "The Banyan Retreat Resort",
    category: "4-star",
    starRating: 4,
    priceRange: {
      minPriceINR: 7000,
      maxPriceINR: 8000,
      priceDisplay: "₹7,000 – ₹8,000",
      priceNote: "Per room / night — cottage & log hut options (breakfast included)",
    },
    location: {
      area: "Chhoi, Near Hanuman Dham",
      address: "Santoshpur, Near Hanuman Dham, Chhoi, Ramnagar, Nainital, Uttarakhand - 244715",
      distanceFromStation: "6 km from Ramnagar Railway Station",
      nearestSafariGates: ["Dhela Safari Gate (8 km)", "Jhirna Safari Gate (9 km)"],
      riverFront: false,
      riverProximity: "Overlooks seasonal forest streams and Sal woodland foothills",
    },
    tagline: "Rustic wooden log-huts and lush landscaped lawns near Hanuman Dham",
    overview:
      "The Banyan Retreat is a scenic 4-star nature resort located in Chhoi, right next to the famed Hanuman Dham spiritual landmark on the southwestern periphery of Jim Corbett. Spread across vast green grounds, the property stands out for its authentic wooden log huts and chalets surrounded by native banyan and sal trees. Facilities include a sprawling outdoor swimming pool, wellness spa, cycling circuits, children's recreation club, and expansive celebration lawns.",
    amenities: [
      "Grand Outdoor Swimming Pool",
      "Ayurvedic Spa & Wellness Pavilion",
      "Multi-Cuisine Garden Restaurant",
      "Dedicated Kids' Club & Children's Play Zone",
      "Cycling Track & Bicycles for Rent",
      "Grand Wedding Lawns & Banquet Facilities",
      "Evening Jungle Bonfires & Barbecue",
      "Indoor Sports & Activity Center",
      "High-Speed Wi-Fi in Public Areas",
      "Free Parking & Driver Accommodation",
    ],
    roomTypes: [
      "Authentic Wooden Log Hut",
      "Royal Banyan Luxury Suite",
      "Forest View Family Cottage",
    ],
    checkInTime: "01:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Unique Canadian-style wooden log huts offering charming wilderness ambiance",
      "Situated next to the architectural marvel of Hanuman Dham temple in Chhoi",
      "Sprawling lawns perfect for large family reunions, weddings, and group stays",
      "Quiet forest boundary location away from highway vehicular noise",
    ],
    websiteUrl: "https://banyanretreatcorbett.com",
    rating: 4.3,
    reviewCount: 490,
    image:
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "The Banyan Retreat Jim Corbett — Wooden Log Huts in Chhoi",
    seoDescription:
      "Book The Banyan Retreat near Hanuman Dham, Chhoi, Ramnagar. Wooden log chalets, swimming pool, luxury spa, expansive wedding lawns from ₹7,000–₹8,000/night.",
    seoKeywords: [
      "banyan retreat corbett",
      "the banyan retreat resort chhoi",
      "wooden log huts jim corbett",
      "resorts near hanuman dham ramnagar",
      "resorts near jhirna dhela",
    ],
  },
  {
    id: "pratiksha-river-retreat",
    slug: "pratiksha-river-retreat",
    name: "Pratiksha River Retreat",
    category: "4-star",
    starRating: 4,
    priceRange: {
      minPriceINR: 6000,
      maxPriceINR: 7000,
      priceDisplay: "₹6,000 – ₹7,000",
      priceNote: "Per room / night — double occupancy on CP plan",
    },
    location: {
      area: "Dhikuli, Riverbank",
      address: "Ranikhet Road, Dhikuli, Jim Corbett National Park, Ramnagar, Nainital, Uttarakhand - 244715",
      distanceFromStation: "10 km from Ramnagar Railway Station",
      nearestSafariGates: ["Garjiya Safari Gate (2 km)", "Bijrani Safari Gate (5.5 km)"],
      riverFront: true,
      riverProximity: "Perched right along the gushing waters of Kosi River",
    },
    tagline: "Serene riverside retreat with direct steps to the crystalline Kosi waters",
    overview:
      "Pratiksha River Retreat is an idyllic 4-star boutique sanctuary situated in Dhikuli near the revered Garjiya Devi Temple. The property is designed to maximize river views, with stone pathways leading right down to the river bank where guests can dip their feet in the clear flowing Kosi waters. Featuring comfortable valley-facing cottages, an open-air swimming pool, riverside multi-cuisine dining, and evening folk dance performances, it delivers classic Corbett riverside charm.",
    amenities: [
      "Direct Stone Walkway to Kosi River Bed",
      "Outdoor Swimming Pool Overlooking the River",
      "Riverside Multi-Cuisine Restaurant",
      "Live Kumaoni Folk Dance & Musical Evenings",
      "Riverside Nature Trails & Guided Birdwatching",
      "Bonfire Nights with Star Gazing",
      "Conference & Meeting Hall",
      "24-Hour Front Desk & Power Backup",
      "Free High-Speed Wi-Fi",
      "Complimentary Self & Valet Parking",
    ],
    roomTypes: [
      "Luxury River Facing Cottage",
      "Premium Valley View Room",
      "Executive River Suite with Balcony",
    ],
    checkInTime: "12:30 PM",
    checkOutTime: "10:30 AM",
    highlights: [
      "Private stone stairway providing immediate access to the Kosi riverbed",
      "Proximity to Garjiya Devi Temple (just 2 km away)",
      "Traditional Kumaoni folk performances organized around the evening bonfire",
      "High rating among families seeking peaceful riverside relaxation",
    ],
    rating: 4.2,
    reviewCount: 460,
    image:
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "Pratiksha River Retreat Dhikuli — Riverside Cottages in Jim Corbett",
    seoDescription:
      "Stay at Pratiksha River Retreat in Dhikuli on the Kosi River bank. Direct river access, swimming pool, folk dance evenings, rooms from ₹6,000–₹7,000/night.",
    seoKeywords: [
      "pratiksha river retreat corbett",
      "pratiksha resort dhikuli",
      "kosi river resort ramnagar",
      "resorts near garjiya temple",
      "riverside cottage jim corbett",
    ],
  },

  // ==========================================
  // 5-STAR / LUXURY CATEGORY (₹8,000 – ₹19,000 / night)
  // ==========================================
  {
    id: "debus-the-fern-resort",
    slug: "debus-the-fern-resort",
    name: "Debu's The Fern Resort & Spa",
    category: "5-star",
    starRating: 5,
    priceRange: {
      minPriceINR: 8000,
      maxPriceINR: 9000,
      priceDisplay: "₹8,000 – ₹9,000",
      priceNote: "Per room / night — 5-star eco-certified luxury (taxes extra)",
    },
    location: {
      area: "Patkote, Forest Reserve",
      address: "Village Patkote, Ramnagar-Haldwani Road, Corbett Reserve Forest, Nainital, Uttarakhand - 263159",
      distanceFromStation: "16 km from Ramnagar Railway Station",
      nearestSafariGates: ["Sitavani Safari Zone (3 km)", "Bijrani Gate (15 km)"],
      riverFront: false,
      riverProximity: "Surrounded by mountain springs and pristine Corbett Reserve Forest",
    },
    tagline: "Eco-certified 5-star forest resort boasting the largest swimming pool in Corbett",
    overview:
      "Debu's The Fern Resort & Spa, Jim Corbett, is an upscale 5-star eco-sensitive property located in the secluded forest hamlet of Patkote. Managed by The Fern Hotels & Resorts — India's leading environmentally responsible hotel brand — the resort is encircled by dense reserve forests and mountain horizons. It features over 76 luxurious rooms, the region's largest outdoor swimming pool, the comprehensive 'Flavour' multi-cuisine restaurant, the chic 'Safari Lounge' bar, and expansive wedding lawns like Shakuntalam.",
    amenities: [
      "Region's Largest Outdoor Swimming Pool & Jacuzzi",
      "Full-Service Wellness Spa with Steam & Sauna",
      "'Flavour' All-Day Multi-Cuisine Fine Dining",
      "'Safari Lounge' Signature Restro-Bar",
      "Fully Equipped Modern Gymnasium",
      "Shakuntalam Grand Banquet & Hill View Wedding Lawns",
      "Eco-Sensitive Architecture & Zero Single-Use Plastic Policy",
      "Kids' Play Club & Activity Zone",
      "Complimentary Wi-Fi Throughout Property",
      "Valet Parking & EV Charging Facilities",
    ],
    roomTypes: [
      "Winter Green Room",
      "Fern Club Forest View Room",
      "Fern Classic Suite with Mountain Balcony",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "12:00 PM",
    highlights: [
      "Home to the largest outdoor swimming pool across the entire Corbett region",
      "Certified 5-star eco-resort adhering to strict global environmental standards",
      "Nestled in Patkote forest valley away from all city hustle and tourist traffic",
      "Shakuntalam banquet grounds ideal for royal destination weddings and offsites",
    ],
    websiteUrl: "https://fernhotels.com",
    rating: 4.6,
    reviewCount: 610,
    image:
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Debu's The Fern Resort & Spa Corbett — 5-Star Eco Luxury in Patkote",
    seoDescription:
      "Experience Debu's The Fern Resort & Spa in Patkote. 5-star eco-luxury, Corbett's largest pool, full spa, fine dining, wedding lawns from ₹8,000–₹9,000/night.",
    seoKeywords: [
      "debus the fern resort corbett",
      "the fern resort jim corbett",
      "5 star resort in patkote",
      "eco luxury resort corbett",
      "largest swimming pool resort corbett",
    ],
  },
  {
    id: "vandhara-sarovar-premier-resort",
    slug: "vandhara-sarovar-premier-resort",
    name: "Vandhara Sarovar Premiere Resort",
    category: "5-star",
    starRating: 5,
    priceRange: {
      minPriceINR: 9000,
      maxPriceINR: 10000,
      priceDisplay: "₹9,000 – ₹10,000",
      priceNote: "Per room / night — luxury premiere inventory with breakfast included",
    },
    location: {
      area: "Patkote, Sitavani Road",
      address: "Sitavani Road, Village Patkote, Ramnagar, Nainital, Uttarakhand - 263159",
      distanceFromStation: "18 km from Ramnagar Railway Station",
      nearestSafariGates: ["Sitavani Safari Gate (4 km)", "Bijrani Gate (17 km)"],
      riverFront: false,
      riverProximity: "Perched high in pristine foothill valley with natural mountain streams",
    },
    tagline: "Ultra-luxurious wilderness haven nestled along the Sitavani reserve corridor",
    overview:
      "Vandhara Sarovar Premiere is the flagship 5-star luxury brand under Sarovar Hotels, situated in the tranquil wilderness along Sitavani Road in Patkote. Built for discerning travelers who demand elevated luxury alongside untouched wilderness, the property offers grand rooms and royal suites with private forest-view balconies. Guests indulge in an infinity-edge pool, premier holistic spa therapies, curated Kumaoni and international culinary fare, and stargazing evenings around the central fire pit.",
    amenities: [
      "Infinity-Edge Swimming Pool & Separate Kids' Pool",
      "Luxury Wellness Spa & Hydrotherapy Sessions",
      "Brahmkamal All-Day Fine-Dining Restaurant",
      "Somras Signature Lounge Bar & Sunset Deck",
      "Nakshatra Grand Banquet Hall & Lawns",
      "State-of-the-Art Gymnasium & Yoga Pavilion",
      "Guided Sitavani Nature Trails & Birdwatching Walks",
      "24-Hour Concierge & Valet Service",
      "Complimentary High-Speed Wi-Fi",
      "Doctor on Call & Power Backup",
    ],
    roomTypes: [
      "Premiere Valley View Room",
      "Luxury Heritage Cottage Suite",
      "Presidential Forest Suite with Terrace",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Flagship 'Sarovar Premiere' 5-star brand offering top-tier hospitality standards",
      "Serene Sitavani forest boundary location offering complete peace and privacy",
      "Infinity swimming pool looking out over uninterrupted sal forest hills",
      "Nakshatra event venues customized for luxury destination celebrations",
    ],
    websiteUrl: "https://sarovarhotels.com",
    rating: 4.6,
    reviewCount: 480,
    image:
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Vandhara Sarovar Premiere Resort Patkote — 5-Star Luxury Corbett",
    seoDescription:
      "Discover Vandhara Sarovar Premiere on Sitavani Road, Patkote. 5-star luxury suites, infinity pool, premier spa, royal dining from ₹9,000–₹10,000/night.",
    seoKeywords: [
      "vandhara sarovar premier resort",
      "sarovar premiere corbett",
      "luxury resort patkote sitavani",
      "5 star hotel sitavani road",
      "infinity pool resort jim corbett",
    ],
  },
  {
    id: "the-taj-corbett",
    slug: "the-taj-corbett",
    name: "Taj Corbett Resort & Spa",
    category: "5-star",
    starRating: 5,
    priceRange: {
      minPriceINR: 16000,
      maxPriceINR: 17000,
      priceDisplay: "₹16,000 – ₹17,000",
      priceNote: "Per room / night — luxury cottage inventory (world-class IHCL hospitality)",
    },
    location: {
      area: "Zero Garjia, Dhikuli",
      address: "Near Zero Garjia, Dhikuli, Jim Corbett, Ramnagar, Uttarakhand - 244715",
      distanceFromStation: "10 km from Ramnagar Railway Station",
      nearestSafariGates: ["Garjiya Gate (2 km)", "Bijrani Gate (6 km)"],
      riverFront: true,
      riverProximity: "Front-row riverbank location along the Kosi River",
    },
    tagline: "Iconic IHCL luxury nestled in a 10-acre century-old mango orchard by the Kosi River",
    overview:
      "Taj Corbett Resort & Spa is the pinnacle of luxury wilderness hospitality in Jim Corbett. Set within a 10-acre estate shaded by century-old mango and jamun trees along the Kosi River, this legendary property brings the iconic Taj hospitality to the Himalayan foothills. Guests stay in stone-and-thatch cottages, indulge in bespoke Ayurvedic therapies at the renowned J Wellness Circle (Jiva Spa), and dine across four distinct venues including the romantic Treetop, Jim's Grill, and the classic Tusker Bar.",
    amenities: [
      "J Wellness Circle (Award-Winning Jiva Luxury Spa)",
      "Outdoor Riverfront Swimming Pool with Sun Loungers",
      "Treetop Fine-Dining Multi-Cuisine Restaurant",
      "Jim's Grill Specialty Open-Air Dining",
      "Tusker Bar & Poolside Cocktail Lounge",
      "Bespoke Wildlife Safaris with Veteran Naturalists",
      "Kosi Lawn & Regal Event Banqueting Venues",
      "Fully Equipped High-Tech Fitness Center & Yoga Deck",
      "High-Speed Wi-Fi & 24/7 Taj Butler/Concierge Service",
      "Electric Vehicle (EV) Charging Station & Luxury Chauffeur Fleet",
    ],
    roomTypes: [
      "Superior Cottage Garden View",
      "Deluxe Cottage River View",
      "Premium Corbett Suite with Private Lawn",
    ],
    checkInTime: "02:00 PM",
    checkOutTime: "12:00 PM",
    highlights: [
      "Legendary Taj hospitality with bespoke wildlife naturalist guidance",
      "Four distinct culinary venues: Treetop, Jim's Grill, Tusker Bar & Pool Bar",
      "Signature J Wellness Circle spa offering authentic Indian healing therapies",
      "Over 10 acres of pristine riverfront nature inhabited by over 100 bird species",
    ],
    websiteUrl: "https://tajhotels.com",
    rating: 4.8,
    reviewCount: 1450,
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Taj Corbett Resort & Spa Dhikuli — 5-Star Luxury Wilderness Resort",
    seoDescription:
      "Book Taj Corbett Resort & Spa in Dhikuli. 5-star IHCL luxury on the Kosi riverbank. J Wellness Circle, Treetop dining, luxury cottages from ₹16,000–₹17,000/night.",
    seoKeywords: [
      "taj corbett resort and spa",
      "taj hotel jim corbett",
      "the taj corbett",
      "5 star luxury resort in dhikuli",
      "luxury resort kosi river taj",
    ],
  },
  {
    id: "jw-marriott-corbett",
    slug: "jw-marriott-corbett",
    name: "Jim Corbett Marriott Resort & Spa",
    category: "5-star",
    starRating: 5,
    priceRange: {
      minPriceINR: 18000,
      maxPriceINR: 19000,
      priceDisplay: "₹18,000 – ₹19,000",
      priceNote: "Per room / night — global 5-star Marriott luxury standard",
    },
    location: {
      area: "Dhikuli, Ranikhet Road",
      address: "Village Dhikuli, Ranikhet Road, Jim Corbett National Park, Ramnagar, Uttarakhand - 244715",
      distanceFromStation: "8.4 km from Ramnagar Railway Station",
      nearestSafariGates: ["Bijrani Gate (4 km)", "Garjiya Gate (3.2 km)"],
      riverFront: true,
      riverProximity: "Front-line vistas of the Kosi River and surrounding forest cliffs",
    },
    tagline: "International 5-star luxury benchmark with private plunge pool suites",
    overview:
      "Jim Corbett Marriott Resort & Spa (frequently referred to as JW Marriott Corbett) defines ultra-modern luxury in the Corbett region. Overlooking the sparkling Kosi River in Dhikuli, the property pairs sleek contemporary design with the raw power of the surrounding forest. Offering opulent suites with private plunge pools, a world-class signature spa with sauna/steam rituals, an all-day global restaurant, arcade gaming zone, and a dedicated kids' club, it is the premiere destination for travelers seeking global luxury standards.",
    amenities: [
      "Year-Round Outdoor Swimming Pool & Separate Heated Kids' Pool",
      "Signature Quan Spa with Sauna & Steam Rituals",
      "Malani Grill Specialty Outdoor Riverside Dining",
      "Sal Bar & Cocktail Lounge",
      "Private Plunge Pools in Executive & River Suites",
      "High-Tech Fitness Center with Matrix Equipment",
      "Modern Interactive Kids' Club & Family Activity Center",
      "Arcade Gaming Zone with Billiards & VR Games",
      "Grand Ballroom & River Terrace for Elite Gatherings",
      "Full Accessibility (Braille, Tactile Signage, Lowered Sinks)",
      "24-Hour International Concierge & Chauffeur Fleet",
    ],
    roomTypes: [
      "Deluxe Mountain View King Room",
      "Executive Suite with River View",
      "Presidential Villa with Private Plunge Pool",
    ],
    checkInTime: "03:00 PM",
    checkOutTime: "12:00 PM",
    highlights: [
      "Marriott Bonvoy global luxury standard in the heart of Jim Corbett",
      "Exclusive suites featuring heated private riverside plunge pools",
      "World-class hydrotherapy spa and high-tech fitness studio",
      "Convenient Dhikuli location with rapid access to Bijrani and Garjiya gates",
    ],
    websiteUrl: "https://marriott.com",
    rating: 4.8,
    reviewCount: 920,
    image:
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Jim Corbett Marriott Resort & Spa Dhikuli — 5-Star Luxury Hotel",
    seoDescription:
      "Experience Marriott luxury in Jim Corbett National Park. 5-star suites with private plunge pools, world-class spa, Kosi river views from ₹18,000–₹19,000/night.",
    seoKeywords: [
      "jw marriott corbett",
      "jim corbett marriott resort and spa",
      "marriott hotel ramnagar",
      "5 star resort in jim corbett with plunge pool",
      "luxury hotel in dhikuli marriott",
    ],
  },
  {
    id: "solluna-resort",
    slug: "solluna-resort",
    name: "The Solluna Resort",
    category: "5-star",
    starRating: 5,
    priceRange: {
      minPriceINR: 14000,
      maxPriceINR: 15000,
      priceDisplay: "₹14,000 – ₹15,000",
      priceNote: "Per room / night — themed sensory cottage accommodations (all meals options)",
    },
    location: {
      area: "Marchula Valley, Ramganga River",
      address: "National Highway 309, Marchula, Pauri Garhwal / Corbett Periphery, Uttarakhand - 244715",
      distanceFromStation: "35 km from Ramnagar Railway Station",
      nearestSafariGates: ["Durgadevi Safari Gate (12 km)", "Dhikala Gate (20 km)"],
      riverFront: true,
      riverProximity: "Fronting the pristine emerald waters of the Ramganga River",
    },
    tagline: "Sensory nature sanctuary themed around the 5 elements in the pristine Marchula Valley",
    overview:
      "The Solluna Resort is an exceptional 5-star wilderness sanctuary located in the untouched Marchula Valley, 35 km away from the busy tourist hub of Ramnagar. Positioned directly on the pebble banks of the Ramganga River where the water runs crystal clear, the resort is architecturally themed around the five human senses and the five primal elements (Earth, Water, Fire, Air, Space). Embracing an intentional digital-detox philosophy, cottages feature private outdoor sit-outs, skylights for stargazing, and panoramic views of the river gorge.",
    amenities: [
      "Scenic Riverfront Swimming Pool with Valley Gorge Panoramas",
      "Multi-Cuisine Fine-Dining Restaurant by the River",
      "Yoga & Meditation Pavilion on the Ramganga Riverbank",
      "Night Stargazing & Bonfire with Dark-Sky Telescopes",
      "Indoor Game Pavilion (Billiards, Table Tennis, Darts, Karaoke)",
      "Riverside Hiking, Trekking & Mountain Biking Trails",
      "Nature-Themed Cottages with Glass Skylights",
      "Conference & Meeting Hall in Valley Setting",
      "Eco-Friendly Practices & Guided Birding Expeditions",
      "Private On-Site Parking & Driver Quarters",
    ],
    roomTypes: [
      "The Touch (Superior Cottage with Pebble Garden)",
      "The Fragrance (Deluxe Cottage with Orchard View)",
      "The Sound (Premier Riverfront Cottage)",
      "The Sight (Presidential Cottage with Stargazing Skylight)",
    ],
    checkInTime: "01:00 PM",
    checkOutTime: "11:00 AM",
    highlights: [
      "Unrivaled location in the pristine Marchula Valley right on the Ramganga River",
      "Architecturally themed around the 5 human senses and 5 natural elements",
      "Crystal-clear river waters with excellent mahseer fish and bird watching",
      "Peaceful digital-detox ambiance far from traffic and commercial crowds",
    ],
    websiteUrl: "https://sollunaresort.com",
    rating: 4.6,
    reviewCount: 1100,
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "The Solluna Resort Marchula — 5-Star Ramganga Riverfront Resort",
    seoDescription:
      "Stay at The Solluna Resort in Marchula Valley on the Ramganga River. 5-star sensory cottages, river gorge views, stargazing, swimming pool from ₹14,000–₹15,000.",
    seoKeywords: [
      "solluna resort corbett",
      "the solluna resort marchula",
      "resorts in marchula ramganga",
      "5 star riverside resort corbett",
      "luxury cottage marchula corbett",
    ],
  },
];
