export const zones = [
  {
    id: "dhikala",
    slug: "dhikala-zone",
    name: "Dhikala Zone",
    zoneType: "Core Zone",
    status: "Seasonal – 15 Nov to 15 Jun",
    tagline: "The deepest core zone in Corbett — day Canter safaris and heritage forest rest houses.",
    description:
      "Dhikala sits 32 km inside Dhangarhi Gate, deep in the heart of Corbett. The open grasslands here — called Chaurs — stretch along the Ramganga reservoir, offering prime opportunities for spotting tigers, wild elephant herds, and gharials. Day visitors experience Dhikala via a 16-person sharing Canter safari bus with pickup and drop at Ramnagar or Dhangarhi Gate. To secure seats, advance booking of at least 15 to 20 days is strongly recommended.",
    gate: "Ramnagar / Dhangarhi Gate (18 km from Ramnagar)",
    season: "15 November to 15 June (closed during monsoon)",
    isOpenNow: true,
    safariModes: ["Canter Safari (16 person sharing)", "Jeep Safari (overnight FRH guests only)"],
    permitQuotaPerShift: { canter: 4, jeep: 30 },
    sightingIndex: "Very High (9.4/10)",
    startingPriceINR: 2299,
    priceNote: "₹2,299 per person (16-person sharing Canter). Pickup/drop: Ramnagar / Dhangarhi Gate. Season: 15 Nov – 15 Jun. Book 15–20 days ahead.",
    highlights: [
      "Day visit Canter Safari (16 person sharing) — ₹2,299/person",
      "Pickup & Drop: Ramnagar / Dhangarhi Gate included",
      "Open season: 15 November to 15 June",
      "Book at least 15 to 20 days in advance for better availability",
      "Dhikala Chaur grasslands & Ramganga reservoir tiger sightings",
    ],
    bestFor: ["Tiger and elephant sightings", "Photography", "Birding", "Day visitors & couples"],
    image:
      "/image/photo-1561731216-c3a4d99437d5.jpg",
    isFeatured: true,
    pricing: {
      perPersonPriceINR: 2299,
      sharingCapacity: "16 person sharing Canter bus",
      bookingWindowNotice: "Book before at least 15 to 20 days for better availability",
      pickupDropNote: "Ramnagar / Dhangarhi Gate",
      inclusions: [
        "Dhikala core-zone entry permit",
        "Confirmed seat on 16-person sharing open Canter bus",
        "Authorized government wildlife guide & driver",
        "Pickup and drop at Ramnagar / Dhangarhi Gate",
      ],
    },
  },
  {
    id: "bijrani",
    slug: "bijrani-zone",
    name: "Bijrani Zone",
    zoneType: "Core Zone",
    status: "High Tiger Activity",
    tagline: "The closest core zone to Ramnagar town — dense sal forest and stellar tiger sighting record.",
    description:
      "Bijrani is just 1 km past Amdanda Gate, making it the easiest core zone to access from Ramnagar. The forest is thick sal, broken by small streams and grassy clearings where deer gather. Tigers are regularly tracked here on morning and afternoon shifts. Safaris are conducted in private 4x4 Gypsies with an authorized forest guide, entry permit, personal jeep, and vehicle hire included. Book more than 5 days ahead to enjoy pre-booking rates with complimentary Ramnagar pickup.",
    gate: "Amdanda Gate, 1 km from Ramnagar",
    season: "15 October to 30 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (9.1/10)",
    startingPriceINR: 7999,
    priceNote: "₹7,999/jeep (pre-booking >5 days, incl. 10 km pickup) | ₹8,499/jeep (within 5 days). Up to 6 persons.",
    highlights: [
      "Pre-booking (>5 days in advance): ₹7,999 / jeep with complimentary 10 km pickup/drop",
      "Current booking (within 5 days of safari): ₹8,499 / jeep",
      "Inclusions: Guide + permit + personal jeep + jeep cost",
      "Consistent tiger sightings, especially on early morning shifts",
    ],
    bestFor: ["First-time visitors", "Families", "Photographers", "Short trips from Delhi"],
    image:
      "/image/photo-1549366021-9f761d450615.jpg",
    isFeatured: true,
    pricing: {
      preBookingPriceINR: 7999,
      currentBookingPriceINR: 8499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar (included with pre-booking)",
      inclusions: [
        "Forest Department core entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop within 10 km of Ramnagar (pre-booking >5 days)",
      ],
    },
  },
  {
    id: "jhirna",
    slug: "jhirna-zone",
    name: "Jhirna Zone",
    zoneType: "Core Zone",
    status: "Open All Year",
    tagline: "Core zone open 365 days — premier sloth bear territory and reliable tiger tracking.",
    description:
      "Jhirna remains open through the monsoon when most other core gates shut down. It was once a village, relocated decades ago; the secondary vegetation and bamboo groves have flourished remarkably. Jhirna boasts one of the highest sloth bear densities in Corbett and active tiger corridors around its year-round waterholes. Available for personal 4x4 Gypsy safaris all year round.",
    gate: "Dhela Gate, 20 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (8.7/10)",
    startingPriceINR: 7999,
    priceNote: "₹7,999/jeep (pre-booking >5 days, incl. 10 km pickup) | ₹8,499/jeep (within 5 days). Up to 6 persons.",
    highlights: [
      "Pre-booking (>5 days in advance): ₹7,999 / jeep with complimentary 10 km pickup/drop",
      "Current booking (within 5 days of safari): ₹8,499 / jeep",
      "Inclusions: Guide + permit + personal jeep + jeep cost",
      "Open all 365 days — premier sloth bear and tiger habitat",
    ],
    bestFor: ["Monsoon travel", "Sloth bear watching", "Year-round wildlife lovers"],
    image: "/jhirna-zone.jpg",
    isFeatured: true,
    pricing: {
      preBookingPriceINR: 7999,
      currentBookingPriceINR: 8499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar (included with pre-booking)",
      inclusions: [
        "Forest Department core entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop within 10 km of Ramnagar (pre-booking >5 days)",
      ],
    },
  },
  {
    id: "dhela",
    slug: "dhela-zone",
    name: "Dhela Zone",
    zoneType: "Core Zone",
    status: "Open All Year",
    tagline: "Quiet core zone with strictly limited daily permits — tranquil tracks and active waterbodies.",
    description:
      "Dhela is an authorized core safari zone located adjacent to Jhirna. Because its permit quota is strictly controlled (15 jeeps per shift), the zone preserves an intimate, quiet wilderness ambiance. Its mixed forest canopy, natural wetlands, and waterholes attract wild elephant herds, tigers, leopards, and rare raptors. Open throughout all twelve months.",
    gate: "Dhela Gate, 20 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 15 },
    sightingIndex: "Moderate to High (8.3/10)",
    startingPriceINR: 7999,
    priceNote: "₹7,999/jeep (pre-booking >5 days, incl. 10 km pickup) | ₹8,499/jeep (within 5 days). Up to 6 persons.",
    highlights: [
      "Pre-booking (>5 days in advance): ₹7,999 / jeep with complimentary 10 km pickup/drop",
      "Current booking (within 5 days of safari): ₹8,499 / jeep",
      "Inclusions: Guide + permit + personal jeep + jeep cost",
      "Strict 15 jeeps/shift cap for an unhurried, private experience",
    ],
    bestFor: ["Quiet safari experience", "Bird watchers", "Second-day safari"],
    image: "/dhela-zone.jpg",
    isFeatured: false,
    pricing: {
      preBookingPriceINR: 7999,
      currentBookingPriceINR: 8499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar (included with pre-booking)",
      inclusions: [
        "Forest Department core entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop within 10 km of Ramnagar (pre-booking >5 days)",
      ],
    },
  },
  {
    id: "garjiya",
    slug: "garjiya-zone",
    name: "Garjiya Zone",
    zoneType: "Core Zone",
    status: "Good Tiger Record",
    tagline: "Rocky riverbeds, boulders, and strong tiger presence along the Kosi corridor.",
    description:
      "Garjiya runs along the Kosi and Ringora riverbeds, just 12 km from Ramnagar. The landscape is striking and rugged — river boulders, sandy flats, and mixed sal forest. Tigers regularly use these river passages to commute between forest ranges, creating frequent and dramatic sightings. Close to major resorts along the Dhikuli strip.",
    gate: "Garjiya Gate, 12 km from Ramnagar",
    season: "15 October to 30 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (8.9/10)",
    startingPriceINR: 7999,
    priceNote: "₹7,999/jeep (pre-booking >5 days, incl. 10 km pickup) | ₹8,499/jeep (within 5 days). Up to 6 persons.",
    highlights: [
      "Pre-booking (>5 days in advance): ₹7,999 / jeep with complimentary 10 km pickup/drop",
      "Current booking (within 5 days of safari): ₹8,499 / jeep",
      "Inclusions: Guide + permit + personal jeep + jeep cost",
      "Rugged Kosi riverbed terrain with excellent predator movements",
    ],
    bestFor: ["Photography", "Guests on Kosi river corridor", "Repeat Corbett visitors"],
    image:
      "/image/photo-1518709268805-4e9042af9f23.jpg",
    isFeatured: true,
    pricing: {
      preBookingPriceINR: 7999,
      currentBookingPriceINR: 8499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar (included with pre-booking)",
      inclusions: [
        "Forest Department core entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop within 10 km of Ramnagar (pre-booking >5 days)",
      ],
    },
  },
  {
    id: "durga-devi",
    slug: "durga-devi-zone",
    name: "Durga Devi Zone",
    zoneType: "Core Zone",
    status: "Best for Birding",
    tagline: "Hilly Himalayan canopy on Corbett's northeastern rim — river gorges, mahseer, and rare raptors.",
    description:
      "Durga Devi sits on the northeastern edge of Corbett, 28 km from Ramnagar. The landscape shifts dramatically into steep foothills, deep gorges, and the confluence of the Mandal and Ramganga rivers. A haven for birdwatchers, mahseer anglers, and those who appreciate breathtaking mountain scenery alongside wildlife tracking.",
    gate: "Durga Devi Gate, 28 km from Ramnagar",
    season: "15 October to 15 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 15 },
    sightingIndex: "Moderate (7.8/10)",
    startingPriceINR: 7999,
    priceNote: "₹7,999/jeep (pre-booking >5 days, incl. 10 km pickup) | ₹8,499/jeep (within 5 days). Up to 6 persons.",
    highlights: [
      "Pre-booking (>5 days in advance): ₹7,999 / jeep with complimentary 10 km pickup/drop",
      "Current booking (within 5 days of safari): ₹8,499 / jeep",
      "Inclusions: Guide + permit + personal jeep + jeep cost",
      "Dramatic river gorges, mahseer pools, and rare bird species",
    ],
    bestFor: ["Serious birders", "Anglers", "Guests wanting hilly forest landscapes"],
    image:
      "/image/photo-1470071459604-3b5ec3a7fe05.jpg",
    isFeatured: false,
    pricing: {
      preBookingPriceINR: 7999,
      currentBookingPriceINR: 8499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar (included with pre-booking)",
      inclusions: [
        "Forest Department core entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop within 10 km of Ramnagar (pre-booking >5 days)",
      ],
    },
  },
  {
    id: "phato",
    slug: "phato-zone",
    name: "Phato Zone",
    zoneType: "Buffer Zone",
    status: "Open All Year",
    tagline: "Buffer zone featuring a forest treehouse stopover — open year-round with reliable tiger sightings.",
    description:
      "Phato is a popular eco-tourism zone located in the Mohan Nagar buffer belt, 26 km from Ramnagar. It operates all 365 days a year. The forest features a distinctive treehouse rest station where guests can take a peaceful break in the canopy. Tiger and elephant encounters have grown steadily here over recent seasons.",
    gate: "Phato Gate, Malkani, 26 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 50 },
    sightingIndex: "High (8.6/10)",
    startingPriceINR: 6499,
    priceNote: "₹6,499/jeep (pre & current booking). Incl. guide + permit + personal jeep + 10 km pickup/drop.",
    highlights: [
      "Fixed price: ₹6,499 / jeep for both pre-booking and current booking",
      "Inclusions: Guide + permit + personal jeep + jeep cost + complimentary 10 km pickup/drop",
      "Forest treehouse stopover point on safari route",
      "Open all 365 days including monsoon months",
    ],
    bestFor: ["Last-minute travelers", "Repeat visitors", "Families and groups"],
    image: "/phato-zone.jpg",
    isFeatured: false,
    pricing: {
      preBookingPriceINR: 6499,
      currentBookingPriceINR: 6499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar",
      inclusions: [
        "Forest entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop from property or location up to 10 km radius from Ramnagar",
      ],
    },
  },
  {
    id: "hathidangar",
    slug: "hathidangar-zone",
    name: "Hathidangar Zone",
    zoneType: "Eco-Tourism Zone",
    status: "Elephant Corridor",
    tagline: "Picturesque forest corridor in Ampokhra range — peaceful safari tracks and high elephant activity.",
    description:
      "Hathidangar (also known as Hathi Dagar) is an eco-tourism safari zone located in the Ampokhra range of Terai West Forest Division, adjacent to Corbett Tiger Reserve. Translating to 'Elephant's Path', this tranquil forested zone offers unhurried safari trails away from crowded routes. Wildlife enthusiasts regularly spot wild elephant herds, leopards, sloth bears, spotted deer, and diverse birds along its natural trails.",
    gate: "Hathidangar Gate / Ampokhra Range, 15 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 25 },
    sightingIndex: "Moderate to High (8.4/10)",
    startingPriceINR: 6499,
    priceNote: "₹6,499/jeep (pre & current booking). Incl. guide + permit + personal jeep + 10 km pickup/drop.",
    highlights: [
      "Fixed price: ₹6,499 / jeep for both pre-booking and current booking",
      "Inclusions: Guide + permit + personal jeep + jeep cost + complimentary 10 km pickup/drop",
      "Prime elephant corridor with pristine mixed forest canopy",
      "Serene trails with capped vehicle movement for a private experience",
    ],
    bestFor: ["Elephant enthusiasts", "Quiet safari experience", "Families & birders", "All-year visits"],
    image:
      "/image/photo-1557050543-4d5f4e07ef46.jpg",
    isFeatured: false,
    pricing: {
      preBookingPriceINR: 6499,
      currentBookingPriceINR: 6499,
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar",
      inclusions: [
        "Forest entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop from property or location up to 10 km radius from Ramnagar",
      ],
    },
  },
  {
    id: "sitabani",
    slug: "sitabani-zone",
    name: "Sitabani Zone",
    zoneType: "Reserve Forest",
    status: "No Quota Cap",
    tagline: "Sacred landscape with multiple gates — flexible bookings and all-weather access.",
    description:
      "Sitabani is an expansive reserve forest bordering Corbett, steeped in Valmiki Ramayana history and rich in Himalayan wildlife. Safari entry is available through three distinct gates: Teda Gate and Bhandarpani Gate at ₹5,999/jeep, and Pawalgarh Gate at ₹6,499/jeep. Not bound by strict core quotas, Sitabani offers easy same-day permit confirmation. All bookings include an authorized guide, permit, personal Gypsy, and hotel pickup/drop within 10 km of Ramnagar.",
    gate: "Teda Gate (₹5,999), Bhandarpani Gate (₹5,999), Pawalgarh Gate (₹6,499)",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 60 },
    sightingIndex: "Moderate (7.5/10)",
    startingPriceINR: 5999,
    priceNote: "₹5,999/jeep (Teda / Bhandarpani Gate) | ₹6,499/jeep (Pawalgarh Gate). Incl. guide, permit & 10 km pickup/drop.",
    highlights: [
      "Teda Gate & Bhandarpani Gate: ₹5,999 / jeep (pre & current booking)",
      "Pawalgarh Gate: ₹6,499 / jeep (pre & current booking)",
      "Inclusions: Guide + permit + personal jeep + jeep cost + complimentary 10 km pickup/drop",
      "Ancient Sita Bani temple inside the forest & year-round availability",
    ],
    bestFor: ["Same-day & flexible plans", "Budget travelers", "Nature walks & birders"],
    image:
      "/image/photo-1448375240586-882707db888b.jpg",
    isFeatured: false,
    pricing: {
      preBookingPriceINR: 5999,
      currentBookingPriceINR: 5999,
      gatePricing: [
        { gate: "Teda Gate", priceINR: 5999 },
        { gate: "Bhandarpani Gate", priceINR: 5999 },
        { gate: "Pawalgarh Gate", priceINR: 6499 },
      ],
      pickupDropNote: "Complimentary pickup/drop from property or any location up to 10 km radius from Ramnagar",
      inclusions: [
        "Forest entry permit",
        "Personal 4x4 Gypsy & fuel/jeep cost",
        "Authorized registered forest guide",
        "Complimentary pickup/drop from property or location up to 10 km radius from Ramnagar",
      ],
    },
  },
];
