export const zones = [
  {
    id: "dhikala",
    slug: "dhikala-zone",
    name: "Dhikala Zone",
    zoneType: "Core Zone",
    status: "Seasonal – Nov to Jun",
    tagline: "The deepest zone in Corbett, open only to overnight guests and day canter visitors.",
    description:
      "Dhikala sits 32 km inside Dhangarhi Gate, deep in the heart of Corbett. The open grasslands here — called Chaurs — stretch along the Ramganga reservoir, and this is where you have a real chance of spotting tigers, elephants, and gharials in the same morning. Day visitors come in by Canter (16-seater bus). Private jeeps are only allowed for guests staying at Dhikala Forest Rest House. The roads are raw and unpaved, and that is exactly the point.",
    gate: "Dhangarhi Gate, 18 km from Ramnagar",
    season: "15 November to 15 June (closed during monsoon)",
    isOpenNow: true,
    safariModes: ["Canter Safari (day visitors)", "Jeep Safari (overnight FRH guests only)"],
    permitQuotaPerShift: { canter: 4, jeep: 30 },
    sightingIndex: "Very High (9.4/10)",
    startingPriceINR: 2400,
    priceNote: "Per seat on Canter (permit + guide included). Jeep rates apply for FRH guests.",
    highlights: [
      "Open grasslands with elephant herds almost every morning",
      "Ramganga reservoir — watch tigers cross the river banks",
      "Dhikala Forest Rest House, built in the British era",
      "Gharials, otters, and mugger crocodiles in the water",
    ],
    bestFor: ["Tiger and elephant sightings", "Photography", "Birding", "Overnight jungle stays"],
    image:
      "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
  },
  {
    id: "bijrani",
    slug: "bijrani-zone",
    name: "Bijrani Zone",
    zoneType: "Core Zone",
    status: "High Tiger Activity",
    tagline: "The closest core zone to Ramnagar town — dense sal forest, good tiger record.",
    description:
      "Bijrani is just 1 km past Amdanda Gate, making it the easiest core zone to reach from Ramnagar. The forest is thick sal, broken by small streams and grassy patches where deer gather. Tigers are regularly tracked here — mostly solo males and a couple of territorial females. Morning shifts get the most action. If this is your first Corbett safari and you want the best shot at a tiger sighting, Bijrani is the right choice.",
    gate: "Amdanda Gate, 1 km from Ramnagar",
    season: "15 October to 30 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (9.1/10)",
    startingPriceINR: 6500,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "Consistent tiger sightings, especially on morning shifts",
      "10 minutes from Ramnagar — no early travel stress",
      "Machan watchtower with wide views over the forest",
      "Good birdlife — over 150 species recorded",
    ],
    bestFor: ["First-time visitors", "Families", "Photographers", "Short trips from Delhi"],
    image:
      "https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
  },
  {
    id: "jhirna",
    slug: "jhirna-zone",
    name: "Jhirna Zone",
    zoneType: "Core Zone",
    status: "Open All Year",
    tagline: "Open 365 days — the go-to zone when other gates are closed in monsoon.",
    description:
      "Jhirna stays open through the monsoon when most other zones shut down. It was once a village, relocated years ago; the forest has grown back well. Sloth bears are the biggest draw here — Jhirna has one of the highest sloth bear densities in Corbett. Tigers pass through regularly too, especially near the waterholes in summer. The bamboo groves and mixed jungle feel different from the sal-heavy Bijrani — worth doing both if you have the time.",
    gate: "Dhela Gate, 20 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (8.7/10)",
    startingPriceINR: 6500,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "Best zone in Corbett for sloth bear encounters",
      "Open during July–September monsoon season",
      "Dense bamboo groves and year-round waterholes",
      "Good raptor sightings in winter months",
    ],
    bestFor: ["Monsoon travel", "Sloth bear watching", "Off-season visitors"],
    image: "/jhirna-zone.jpg",
    isFeatured: true,
  },
  {
    id: "dhela",
    slug: "dhela-zone",
    name: "Dhela Zone",
    zoneType: "Eco-Tourism Zone",
    status: "Open All Year",
    tagline: "Quiet zone with limited daily permits — fewer vehicles, better experience.",
    description:
      "Dhela opened in 2014, next to Jhirna. Because the daily permit quota is lower (only 15 jeeps per shift), this zone stays less crowded than Bijrani. The mixed forest and waterbodies attract spotted deer, leopards, and the occasional tiger. Good for birding too — the open pools bring in herons, kingfishers, and occasionally painted storks. Works well as a second day option if you have done Bijrani already.",
    gate: "Dhela Gate, 20 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 15 },
    sightingIndex: "Moderate to High (8.3/10)",
    startingPriceINR: 6200,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "Only 15 jeeps per shift — less traffic on the tracks",
      "Open year-round, including monsoon",
      "Waterbodies with good waterbird activity",
      "Elephant herds pass through regularly",
    ],
    bestFor: ["Quiet safari experience", "Bird watchers", "Second-day safari"],
    image: "/dhela-zone.jpg",
    isFeatured: false,
  },
  {
    id: "garjiya",
    slug: "garjiya-zone",
    name: "Garjiya Zone",
    zoneType: "Core Zone",
    status: "Good Tiger Record",
    tagline: "Rocky riverbeds, boulders, and strong tiger presence along the Kosi corridor.",
    description:
      "Garjiya runs along the Kosi and Ringora riverbeds, 12 km from Ramnagar. The terrain is rocky and varied — boulders, sandy banks, and mixed forest. Tigers use these river corridors to move between ranges, which makes for some good sightings. Lately, a tigress with cubs has been active in this zone. Most of the big resorts along the Kosi river are close by, so guests get back to their property in under 20 minutes after a safari.",
    gate: "Garjiya Gate, 12 km from Ramnagar",
    season: "15 October to 30 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 30 },
    sightingIndex: "High (8.9/10)",
    startingPriceINR: 6500,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "Rocky Kosi riverbed terrain — different landscape from other zones",
      "Tigress with cubs active in recent seasons",
      "Less busy than Bijrani on most days",
      "Convenient for guests staying at Kosi river resorts",
    ],
    bestFor: ["Photography", "Guests on Kosi river corridor", "Repeat Corbett visitors"],
    image:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
  },
  {
    id: "durga-devi",
    slug: "durga-devi-zone",
    name: "Durga Devi Zone",
    zoneType: "Hill Zone",
    status: "Best for Birding",
    tagline: "Hilly terrain on Corbett's northeast edge — not for tigers, perfect for birds and anglers.",
    description:
      "Durga Devi is on the northeastern edge of Corbett, 28 km from Ramnagar. The landscape changes completely here — steep hills, river gorges, and the Mandal and Ramganga rivers joining. Tiger sightings are rare, but if you are a birder or a fly-fishing enthusiast, this is the zone for you. Mahseer — the game fish of the Himalayas — breed in these cold, clear waters. Rare birds like the Grey-headed Fish Eagle and Crested Laughingthrush are spotted here regularly.",
    gate: "Durga Devi Gate, 28 km from Ramnagar",
    season: "15 October to 15 June",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 15 },
    sightingIndex: "Moderate (7.8/10)",
    startingPriceINR: 7000,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "River gorges and hill canopy — completely different scenery",
      "Mahseer fishing on Ramganga and Mandal rivers (catch & release)",
      "Grey-headed Fish Eagle, Crested Laughingthrush, and other rare birds",
      "Wild elephant crossings along river corridors",
    ],
    bestFor: ["Serious birders", "Anglers", "Guests wanting something different from the usual zones"],
    image:
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
  },
  {
    id: "phato",
    slug: "phato-zone",
    name: "Phato Zone",
    zoneType: "Buffer Zone",
    status: "Open All Year",
    tagline: "Buffer zone with a treehouse stopover — open year-round, easier to book last minute.",
    description:
      "Phato is Corbett's newest tourism zone, located in the Mohan Nagar buffer belt, 26 km from Ramnagar. It has 50 jeep slots per shift — more than most other zones — so last-minute permits are often available when Bijrani and Dhikala are already full. There is a treehouse rest point inside the forest where the guide stops for a break. Tiger sightings have been increasing here over the last couple of seasons. A solid backup option that often ends up being a pleasant surprise.",
    gate: "Phato Gate, Malkani, 26 km from Ramnagar",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 50 },
    sightingIndex: "High (8.6/10)",
    startingPriceINR: 6200,
    priceNote: "Per jeep, up to 6 guests (permit + guide + vehicle included)",
    highlights: [
      "Treehouse stopover inside the forest during the safari",
      "More slots available — good for last-minute bookings",
      "Open through monsoon",
      "Dense spotted deer and wild boar populations",
    ],
    bestFor: ["Last-minute travelers", "Repeat visitors", "Families and groups"],
    image: "/phato-zone.jpg",
    isFeatured: false,
  },
  {
    id: "sitabani",
    slug: "sitabani-zone",
    name: "Sitabani Zone",
    zoneType: "Reserve Forest",
    status: "No Quota Cap",
    tagline: "Not under Project Tiger rules — permits available same day, open all year.",
    description:
      "Sitabani is a reserve forest, not under the strict Project Tiger jurisdiction that governs the core zones. This means the daily permit cap does not apply here, and you can often book on the same day you want to go. It is also cheaper than the core zones. There is a historic Sita Bani temple inside the forest. Leopards, deer, and some tigers use this area. Short nature walks with an armed escort are allowed in designated buffer patches — something you cannot do in the core zones.",
    gate: "Near Teda Village / Bhandarpani Gate",
    season: "Open all 365 days",
    isOpenNow: true,
    safariModes: ["Jeep Safari (exclusive 4x4)"],
    permitQuotaPerShift: { jeep: 60 },
    sightingIndex: "Moderate (7.5/10)",
    startingPriceINR: 5500,
    priceNote: "Per jeep, up to 6 guests (private forest permit + guide included)",
    highlights: [
      "Ancient Sita Bani temple inside the forest",
      "Short guided walks allowed in buffer zones",
      "Same-day booking almost always possible",
      "Large herds of sambar, cheetal, and barking deer",
    ],
    bestFor: ["Same-day or last-minute plans", "Budget travelers", "Guests wanting a nature walk"],
    image:
      "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
  },
];
