export const packages = [
  {
    id: "dhikala-frh-immersion",
    slug: "dhikala-frh-2n-3d",
    title: "Dhikala Forest Rest House — 2 Nights",
    subtitle: "Stay inside the core zone with 4 private safaris included",
    duration: "2 Nights / 3 Days",
    zone: "Dhikala Core Zone",
    safariCount: "4 private Gypsy safaris",
    accommodation: "Dhikala or Gairal Forest Rest House",
    startingPriceINR: 28500,
    priceDisplay: "₹28,500",
    priceNote: "Per couple — FRH stay, all meals, Gypsy permits and guide included",
    badge: "Permits Required 45 Days in Advance",
    scarcityText: "Very few rooms, quota opens exactly 45 days before arrival date.",
    overview:
      "After 4:30 PM, the day visitors leave Dhikala and the gates close. From that point until the next morning, the only people in the core forest are the guests staying at the FRH. You hear the jungle settle into night — alarm calls, distant elephants, the Ramganga flowing below the machan. It is a different experience from a day safari. Four private Gypsy safaris are included across your three days, so you have time in the forest both morning and evening.",
    inclusions: [
      "2 nights at Dhikala or Gairal Forest Rest House",
      "4 private Gypsy safaris with a naturalist",
      "All Forest Department fees — entry, road, and housekeeping",
      "All vegetarian meals at the FRH canteen",
      "Ramnagar pickup and drop in private Gypsy",
    ],
    exclusions: [
      "Mineral water and personal tips",
      "Travel to/from Ramnagar station or airport",
    ],
    itineraryHighlights: [
      "Day 1: Enter Dhangarhi Gate by afternoon, check in at FRH, evening safari on Sambar Road",
      "Day 2: Dawn safari to Dhikala Chaur and Ramganga bank, rest midday, evening safari",
      "Day 3: Sunrise drive, breakfast at canteen, checkout and exit by Dhangarhi Gate",
    ],
    image:
      "https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Dhikala Forest Rest House Package — 2 Night 3 Day | Jim Corbett",
    seoDescription:
      "Book Dhikala FRH immersion package — 2 nights inside Jim Corbett core zone, 4 private Gypsy safaris, all meals and Forest Rest House stay. ₹28,500/couple. Forest Department permits open 45 days ahead. Licensed operator.",
    seoKeywords: [
      "dhikala forest rest house booking",
      "dhikala frh package",
      "jim corbett overnight stay inside core zone",
      "dhikala 2 night 3 day package",
      "dhikala forest rest house price",
      "jim corbett frh immersion package",
    ],
  },
  {
    id: "bijrani-tiger-weekend",
    slug: "bijrani-weekend-safari",
    title: "Bijrani Weekend — 1 Night",
    subtitle: "Two jeep safaris in Bijrani with a jungle resort stay",
    duration: "1 Night / 2 Days",
    zone: "Bijrani Zone",
    safariCount: "2 private jeep safaris",
    accommodation: "Luxury jungle resort near Ramnagar",
    startingPriceINR: 11500,
    priceDisplay: "₹11,500",
    priceNote: "Per couple — resort stay + 2 safaris + meals included",
    badge: "Best Tiger Sighting Record",
    scarcityText: "Bijrani morning permits cap at 30 jeeps per shift.",
    overview:
      "Built for a Delhi-to-Corbett weekend. You arrive Friday, do an afternoon safari in Bijrani, have dinner at the resort, wake up early Saturday for the morning safari, then drive back after breakfast. Both safaris are in Bijrani, which has the most consistent tiger sighting record of any zone accessible by day jeep. One resort night is included with breakfast and dinner.",
    inclusions: [
      "1 night at a 4-star jungle resort near Ramnagar",
      "2 private Gypsy safaris in Bijrani zone with certified guide",
      "Resort breakfast and dinner",
      "All gate fees, permit charges, and jeep hire",
    ],
    exclusions: ["Lunch on Day 1", "Personal expenses"],
    itineraryHighlights: [
      "Day 1: Check in by 12:30 PM, afternoon Bijrani safari (2:00–5:30 PM), dinner at resort",
      "Day 2: Morning Bijrani safari (6:00–9:30 AM), breakfast, check-out and return",
    ],
    image:
      "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    seoTitle: "Bijrani Weekend Safari Package — 1 Night | Delhi to Jim Corbett",
    seoDescription:
      "Best Delhi to Jim Corbett weekend package — 1 night jungle resort + 2 private Bijrani jeep safaris from ₹11,500/couple. Highest tiger sighting zone. Permits, guide & breakfast included. Book online.",
    seoKeywords: [
      "bijrani weekend package",
      "delhi to jim corbett weekend package",
      "jim corbett 1 night 2 day package",
      "bijrani resort safari package",
      "jim corbett weekend trip from delhi",
      "delhi corbett weekend getaway",
    ],
  },
  {
    id: "double-zone-day-safari",
    slug: "corbett-double-zone-safari",
    title: "Double Zone Day Safari",
    subtitle: "Morning and afternoon safaris in two different zones, same day",
    duration: "Full Day (same day)",
    zone: "Bijrani + Garjiya or Jhirna",
    safariCount: "2 private Gypsy safaris",
    accommodation: "No stay (day excursion)",
    startingPriceINR: 12800,
    priceDisplay: "₹12,800",
    priceNote: "Per jeep (up to 6 people) — both safaris, permits, and guide included",
    badge: "Best Sighting Chances",
    scarcityText: "Needs two separate zone permits to be coordinated.",
    overview:
      "If you only have one day in Corbett, this gets you twice the forest time. Morning shift in Bijrani, return to Ramnagar for rest and lunch, then afternoon shift in Garjiya or Jhirna. Different zone, different terrain, different animals potentially. Good for photographers who want light from both ends of the day, and for anyone who does not want to leave anything to chance.",
    inclusions: [
      "Morning jeep safari in Bijrani zone",
      "Afternoon jeep safari in Garjiya or Jhirna zone",
      "Exclusive jeep for up to 6 people",
      "Both zone permits, gate fees, and naturalist for the day",
    ],
    exclusions: ["No accommodation or meals included"],
    itineraryHighlights: [
      "5:45 AM: Pickup for morning safari",
      "10:00 AM: Return — rest and lunch in Ramnagar (own account)",
      "1:45 PM: Pickup for afternoon safari in second zone",
    ],
    image:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    isFeatured: false,
    seoTitle: "Jim Corbett Double Zone Day Safari | Bijrani + Garjiya | ₹12,800/Jeep",
    seoDescription:
      "Two safaris in two Jim Corbett zones in one day — morning Bijrani + afternoon Garjiya or Jhirna. ₹12,800/jeep for up to 6 guests. Both permits, guides & private jeep included. Perfect for day visitors from Delhi.",
    seoKeywords: [
      "jim corbett double zone safari",
      "two zone safari jim corbett",
      "morning evening safari corbett",
      "bijrani garjiya safari day trip",
      "jim corbett full day safari package",
      "jim corbett day trip from delhi",
    ],
  },
  {
    id: "dhikala-day-canter",
    slug: "dhikala-canter-day-trip",
    title: "Dhikala Canter Day Trip",
    subtitle: "Day access to the Dhikala core zone by 16-person sharing safari bus",
    duration: "Half day (5 hours)",
    zone: "Dhikala Core Zone",
    safariCount: "1 Canter safari (16 person sharing)",
    accommodation: "No stay (day excursion)",
    startingPriceINR: 2299,
    priceDisplay: "₹2,299",
    priceNote: "Per person / seat (16-person sharing Canter) — entry permit, guide & pickup/drop included",
    badge: "Seasonal (15 Nov – 15 Jun)",
    scarcityText: "Strictly 4 Canters per shift. Book at least 15 to 20 days in advance.",
    overview:
      "The official day access route into Dhikala — Corbett's celebrated core zone (open 15 November to 15 June). You book a confirmed seat on the 16-person sharing Canter safari bus with pickup and drop at Ramnagar or Dhangarhi Gate. Travel 32 km through pristine sal forest into the Ramganga river valley. Please book at least 15 to 20 days in advance for best availability.",
    inclusions: [
      "Official Dhikala core entry permit",
      "Confirmed seat on 16-person sharing open Canter bus",
      "Government-appointed wildlife guide & driver",
      "Pickup and drop at Ramnagar / Dhangarhi Gate",
    ],
    exclusions: ["Personal expenses & tips"],
    itineraryHighlights: [
      "Pickup from Ramnagar / Dhangarhi Gate",
      "32 km scenic drive through dense sal forest to Dhikala complex",
      "Approximately 2 hours scanning Dhikala Chaur and Ramganga river bank",
    ],
    image: "/dhikala-canter.jpg",
    isFeatured: false,
    seoTitle: "Dhikala Canter Day Trip | ₹2,299/Seat | Jim Corbett Safari",
    seoDescription:
      "Book a seat on the Dhikala canter safari day trip at ₹2,299/person. 16-person sharing open Canter bus into Corbett’s deepest core zone. Season 15 Nov–15 Jun. Only 4 canters/shift — book 15–20 days ahead.",
    seoKeywords: [
      "dhikala canter safari day trip",
      "dhikala canter safari booking",
      "dhikala zone day visitor",
      "jim corbett canter safari price per person",
      "dhikala zone day safari",
      "book dhikala canter safari online",
    ],
  },
];
