export const packages = [
  {
    id: "delhi-corbett-all-inclusive",
    slug: "delhi-to-corbett-tour",
    title: "Delhi to Jim Corbett Package",
    subtitle: "Delhi NCR door-to-door private cab, 3-star resort stay & core safari",
    duration: "1 Night / 2 Days (or 2N/3D)",
    zone: "Bijrani / Garjiya Core Zone",
    safariCount: "1 private Gypsy safari",
    accommodation: "3-star jungle resort near Ramnagar",
    startingPriceINR: 20999,
    priceDisplay: "₹20,999",
    priceNote: "Per couple (1N/2D) — Delhi round-trip AC cab, resort stay, meals & 1 core safari; 2N/3D from ₹24,999",
    badge: "Delhi NCR Doorstep Transfer",
    scarcityText: "Round-trip cab + core safari permits arranged together.",
    overview:
      "Built specifically for Delhi NCR travellers looking for a seamless, 100% arranged Jim Corbett getaway. Your private AC Sedan (Swift Dzire) picks you up directly from your doorstep in Delhi, Gurgaon, Noida, or Ghaziabad and drops you at your Corbett jungle resort. Includes 1 night accommodation at a 3-star resort, breakfast and dinner, and an exclusive private 4x4 Gypsy safari into Bijrani or Garjiya core zone with an authorized naturalist. All highway tolls, state entry taxes, driver allowance, and forest permits are included with zero hidden charges. 2 Night / 3 Day extension available from ₹24,999/couple.",
    inclusions: [
      "Round-trip private AC Sedan (Swift Dzire) transfer from Delhi NCR to Ramnagar and back",
      "1 night accommodation at a 3-star jungle resort (double occupancy)",
      "1 private 4x4 Gypsy safari in Bijrani or Garjiya core zone",
      "Authorized Forest Department guide & core entry permit",
      "Resort breakfast and dinner (MAP plan)",
      "All highway tolls, state road permits, driver night allowances & parking",
      "Doorstep pickup & drop in Delhi, Gurgaon, Noida, or Ghaziabad",
    ],
    exclusions: [
      "Lunch and mid-highway meals",
      "Personal expenses and tips",
      "Optional second safari (available as add-on for ₹7,999)",
    ],
    itineraryHighlights: [
      "Day 1 (06:00 AM): Doorstep pickup in Delhi NCR, scenic 5–6 hr drive via NH-9 to Ramnagar",
      "Day 1 (12:30 PM): Check-in at jungle resort, relax and enjoy lunch/afternoon leisure",
      "Day 1 (Evening) or Day 2 (Dawn): Exclusive private 4x4 Gypsy safari in Bijrani/Garjiya core zone",
      "Day 2 (11:00 AM): Resort breakfast, check-out, and comfortable private drive back to Delhi NCR",
    ],
    image:
      "/image/photo-1549366021-9f761d450615.jpg",
    isFeatured: true,
    seoTitle: "Delhi to Jim Corbett Package | Round-Trip Cab + Resort + Safari | ₹20,999/Couple",
    seoDescription:
      "All-inclusive Delhi to Jim Corbett tour package from ₹20,999/couple. Doorstep AC cab from Delhi NCR, jungle resort stay, meals, and private core jeep safari. 2N/3D from ₹24,999. Book online.",
    seoKeywords: [
      "delhi to jim corbett package",
      "jim corbett package from delhi",
      "delhi to corbett tour package with cab",
      "jim corbett weekend trip from delhi",
      "delhi to ramnagar tour package",
      "jim corbett all inclusive package from delhi",
    ],
    resortSlugs: [
      "serenity-resort",
      "wildlife-stayz-by-corbett-treff",
      "corbett-treat-resort",
      "la-perle-river-resort",
      "river-heritage-resort",
    ],
  },
  {
    id: "bijrani-tiger-weekend",
    slug: "bijrani-weekend-safari",
    title: "Bijrani Weekend Safari — 1 Night",
    subtitle: "Private Bijrani core safari with jungle resort stay & meals",
    duration: "1 Night / 2 Days",
    zone: "Bijrani Core Zone",
    safariCount: "1 private Gypsy safari",
    accommodation: "3-star or 4-star jungle resort near Ramnagar",
    startingPriceINR: 11999,
    priceDisplay: "₹11,999",
    priceNote: "Per couple — 1 night 3-star resort, meals & 1 Bijrani core safari included (2-safari option from ₹19,999)",
    badge: "Best Tiger Sighting Record",
    scarcityText: "Bijrani core permits strictly capped at 30 jeeps per shift.",
    overview:
      "The ideal minimum weekend wildlife package for visitors arriving in Ramnagar by train or personal car. Stay 1 night at a selected jungle resort near Ramnagar with breakfast and dinner included, and venture deep into the Bijrani core zone on an exclusive private 4x4 Gypsy safari with a registered Forest Department naturalist. Bijrani holds Corbett's highest day-safari tiger sighting index (9.1/10). Need a second safari? Add an afternoon or morning shift for ₹7,999 (complete 2-safari package at ₹19,999/couple).",
    inclusions: [
      "1 night stay at a 3-star jungle resort near Ramnagar (double occupancy)",
      "1 private 4x4 Gypsy safari in Bijrani core zone with registered naturalist",
      "Resort breakfast and dinner (MAP plan)",
      "All Forest Department entry permits, road taxes, and jeep hire charges",
      "Complimentary pickup and drop from resort to safari gate",
    ],
    exclusions: [
      "Travel to/from Ramnagar (Delhi cab add-on available from ₹9,000 round-trip)",
      "Lunch on Day 1",
      "Optional second safari (available as add-on for ₹7,999)",
    ],
    itineraryHighlights: [
      "Day 1: Arrive in Ramnagar, check in by 12:30 PM, enjoy resort pool and lush surroundings",
      "Day 1 (Afternoon) or Day 2 (Dawn): 3.5-hour private Gypsy safari tracking tigers in Bijrani core",
      "Day 2: Morning breakfast at resort, check-out, and return journey",
    ],
    image:
      "/image/photo-1561731216-c3a4d99437d5.jpg",
    isFeatured: true,
    seoTitle: "Bijrani Weekend Safari Package — 1 Night | ₹11,999/Couple | Jim Corbett",
    seoDescription:
      "Book Bijrani weekend package from ₹11,999/couple. 1 night jungle resort stay + private Bijrani core jeep safari + meals. Best tiger sighting zone. 2 safaris from ₹19,999. Licensed operator.",
    seoKeywords: [
      "bijrani weekend package",
      "delhi to jim corbett weekend package",
      "jim corbett 1 night 2 day package",
      "bijrani resort safari package",
      "corbett budget safari package",
      "bijrani safari price per couple",
    ],
    resortSlugs: [
      "serenity-resort",
      "wildlife-stayz-by-corbett-treff",
      "corbett-treat-resort",
      "river-heritage-resort",
      "la-perle-river-resort",
      "the-taj-corbett",
    ],
  },
  {
    id: "double-zone-day-safari",
    slug: "corbett-double-zone-safari",
    title: "Double Zone Day Safari",
    subtitle: "Morning and afternoon safaris in two different core zones, same day",
    duration: "Full Day (same day)",
    zone: "Bijrani + Garjiya or Jhirna",
    safariCount: "2 private Gypsy safaris",
    accommodation: "No stay (day excursion)",
    startingPriceINR: 15999,
    priceDisplay: "₹15,999",
    priceNote: "Per jeep (up to 6 people) — both core safaris (Bijrani + Garjiya), permits, and guide included",
    badge: "Maximum Sighting Chances",
    scarcityText: "Coordinates two separate core zone permit quotas in one day.",
    overview:
      "If you only have one day in Jim Corbett and want to double your wildlife sighting probability, our Double Zone Day Safari covers two completely distinct forest ecosystems in a single day. Embark on a dawn shift in the dense sal forests of Bijrani (9.1/10 tiger index), return to Ramnagar for midday lunch, then head out on an afternoon shift along the rocky Kosi river corridor of Garjiya or the dry deciduous trails of Jhirna. Both core permits, private 4x4 Gypsy, and registered naturalists are included for up to 6 people.",
    inclusions: [
      "Morning jeep safari in Bijrani core zone (exclusive 4x4 Gypsy)",
      "Afternoon jeep safari in Garjiya or Jhirna core zone (exclusive 4x4 Gypsy)",
      "Exclusive vehicle for up to 6 people per safari",
      "Both Forest Department core entry permits and gate fees",
      "Authorized government naturalist guide for both shifts",
      "Complimentary pickup and drop within 10 km radius of Ramnagar",
    ],
    exclusions: ["No accommodation or meals included (day excursion)", "Personal expenses & tips"],
    itineraryHighlights: [
      "05:45 AM: Pickup for morning Bijrani safari (dense sal forest tiger tracking)",
      "09:30 AM: Return to Ramnagar — midday rest and lunch (own account)",
      "01:45 PM: Pickup for afternoon Garjiya or Jhirna safari (riverbed & elephant territory)",
      "05:30 PM: Return to Ramnagar with double the safari memories",
    ],
    image:
      "/image/photo-1518709268805-4e9042af9f23.jpg",
    isFeatured: false,
    seoTitle: "Jim Corbett Double Zone Day Safari | Bijrani + Garjiya | ₹15,999/Jeep",
    seoDescription:
      "Book two core zone safaris in Jim Corbett in one day — morning Bijrani + afternoon Garjiya or Jhirna. ₹15,999/jeep for up to 6 guests (~₹2,666/person). Both permits, private Gypsies & guides included.",
    seoKeywords: [
      "jim corbett double zone safari",
      "two zone safari jim corbett",
      "morning evening safari corbett",
      "bijrani garjiya safari day trip",
      "jim corbett full day safari package",
      "two safaris in one day corbett",
    ],
  },
  {
    id: "dhikala-frh-immersion",
    slug: "dhikala-frh-2n-3d",
    title: "Dhikala Forest Rest House — 2 Nights",
    subtitle: "Stay inside the core zone with 4 private safaris included",
    duration: "2 Nights / 3 Days",
    zone: "Dhikala Core Zone",
    safariCount: "4 private Gypsy safaris",
    accommodation: "Dhikala or Gairal Forest Rest House",
    startingPriceINR: 35000,
    priceDisplay: "₹35,000",
    priceNote: "Per couple — 2 nights FRH stay, all canteen meals, dedicated Gypsy permits & guide included",
    badge: "Permits Required 45 Days in Advance",
    scarcityText: "Very few rooms; government quota opens exactly 45 days before arrival date.",
    overview:
      "After 4:30 PM, all day visitors depart Dhikala and the gates close. From that point until next morning, the only people inside the core wilderness are the guests staying at the Forest Rest House. You hear the jungle settle into darkness — alarm calls, elephant trumpets across the Ramganga, stars untouched by light pollution. Four private Gypsy safaris are conducted across your 3 days with a dedicated vehicle and registered naturalist. Includes 2 nights at Gairal or Dhikala FRH, all vegetarian canteen meals, and Ramnagar transfers.",
    inclusions: [
      "2 nights stay at Dhikala or Gairal Forest Rest House (double room)",
      "4 private Gypsy safaris inside Dhikala core zone with dedicated naturalist",
      "Dedicated 4x4 Gypsy vehicle inside the core zone for the entire 3 days",
      "All Forest Department entry fees, road permits, and housekeeping surcharges",
      "All vegetarian meals at the Forest Department FRH canteen",
      "Ramnagar pickup and drop via Dhangarhi Gate",
    ],
    exclusions: [
      "Travel to/from Ramnagar (Delhi cab add-on available)",
      "Mineral water and personal tips",
    ],
    itineraryHighlights: [
      "Day 1: Enter Dhangarhi Gate by 12:30 PM, check in at FRH, afternoon safari along Sambar Road",
      "Day 2: Dawn safari to Dhikala Chaur & Ramganga reservoir; midday rest; evening safari to crocodile point",
      "Day 3: Sunrise drive, breakfast at canteen, checkout and exit through Dhangarhi Gate",
    ],
    image:
      "/image/photo-1549366021-9f761d450615.jpg",
    isFeatured: true,
    seoTitle: "Dhikala Forest Rest House Package — 2 Night 3 Day | ₹35,000/Couple",
    seoDescription:
      "Book Dhikala FRH immersion package — 2 nights inside Jim Corbett core zone, 4 private Gypsy safaris, all meals and Forest Rest House stay. ₹35,000/couple. Permits open 45 days ahead.",
    seoKeywords: [
      "dhikala forest rest house booking",
      "dhikala frh package",
      "jim corbett overnight stay inside core zone",
      "dhikala 2 night 3 day package",
      "dhikala forest rest house price",
      "jim corbett frh immersion package",
    ],
  },
  {
    id: "dhikala-day-canter",
    slug: "dhikala-canter-day-trip",
    title: "Dhikala Canter Day Trip",
    subtitle: "Day access to the Dhikala core zone by 16-person sharing safari bus",
    duration: "Half day (5 hours)",
    zone: "Dhikala Core Zone",
    safariCount: "1 Canter safari (16 person sharing)",
    accommodation: "No stay (day excursion)",
    startingPriceINR: 2299,
    priceDisplay: "₹2,299",
    priceNote: "Per person / seat (16-person sharing Canter) — entry permit, guide & pickup/drop included",
    badge: "Seasonal (15 Nov – 15 Jun)",
    scarcityText: "Strictly 4 Canters per shift. Book at least 15 to 20 days in advance.",
    overview:
      "The official day access route into Dhikala — Corbett's celebrated core zone (open 15 November to 15 June). You book a confirmed seat on the 16-person sharing Canter safari bus with pickup and drop at Ramnagar or Dhangarhi Gate. Travel 32 km through pristine sal forest into the Ramganga river valley. Please book at least 15 to 20 days in advance for best availability.",
    inclusions: [
      "Official Dhikala core entry permit",
      "Confirmed seat on 16-person sharing open Canter bus",
      "Government-appointed wildlife guide & driver",
      "Pickup and drop at Ramnagar / Dhangarhi Gate",
    ],
    exclusions: ["Personal expenses & tips"],
    itineraryHighlights: [
      "Pickup from Ramnagar / Dhangarhi Gate",
      "32 km scenic drive through dense sal forest to Dhikala complex",
      "Approximately 2 hours scanning Dhikala Chaur and Ramganga river bank",
    ],
    image: "/dhikala-canter.jpg",
    isFeatured: false,
    seoTitle: "Dhikala Canter Day Trip | ₹2,299/Seat | Jim Corbett Safari",
    seoDescription:
      "Book a seat on the Dhikala canter safari day trip at ₹2,299/person. 16-person sharing open Canter bus into Corbett’s deepest core zone. Season 15 Nov–15 Jun. Only 4 canters/shift — book 15–20 days ahead.",
    seoKeywords: [
      "dhikala canter safari day trip",
      "dhikala canter safari booking",
      "dhikala zone day visitor",
      "jim corbett canter safari price per person",
      "dhikala zone day safari",
      "book dhikala canter safari online",
    ],
  },
];
